### ISSUE TITLE
Just don't work (video included)

### ISSUE THREAD

**Issue by FaceCutter** [gbl/RandomBlockPlacement#12]
https://youtu.be/ru2vFTZ8tqs

**Comment by FaceCutter** [comment]
![image](https://github.com/gbl/RandomBlockPlacement/assets/46198667/3336d949-942a-493d-afd9-ed67a831c66e)
ModList

**Comment by FaceCutter** [comment]
The problem was in this mod:
https://github.com/Siphalor/mouse-wheelie

Does not work on newest version, but the 1.11.1 works just fine!

**Comment by gbl** [comment]
Probably an incompatibility with one of your other mods. Sorry, I won't take the time to install each of them and find if it's the one. It should work if you have only my mods installed.

**Comment by FaceCutter** [comment]
> Probably an incompatibility with one of your other mods. Sorry, I won't take the time to install each of them and find if it's the one. It should work if you have only my mods installed.

Sry for that, the problem was in newest version of Mouse Wheelie (1.12.1)
The 1.11.1 works just fine,

I sended them this information too!

Thanks for fast reply and your beautiful mod <3

**Comment by gbl** [comment]
I just checked the source code of MouseWheelie, it seems like it has some feature to replenish the item that's in your current hotbar slot. Very likely that this interacts with the slot changing in some way.

**Comment by FaceCutter** [comment]
> I just checked the source code of MouseWheelie, it seems like it has some feature to replenish the item that's in your current hotbar slot. Very likely that this interacts with the slot changing in some way.

Yup, it is an all time feature of this mod. But they changed something in 1.12.1 update( 
Anyway, my problem is solved.
Hope this tread will help someone too.
