### ISSUE TITLE
Crashes with Fabric 1.18.2

### ISSUE THREAD

**Issue by jsnee** [gbl/RandomBlockPlacement#7]
Using the current version of Fabric (0.13.3) for Minecraft 1.18.2 this mod crashes with the following error:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3304 failed
Exit Code: -1
```

**Comment by gbl** [comment]
Updated version for 1.18.2 pushed to CF and Modrinth.
